- name: Ping Host
  ping:

- name: Check directory
  stat:
    path: "{{ item }}"
  register: check_1
  ignore_errors: true
  with_items:
    - ~/T01/Test1
    - ~/T01/Test2

- name: msg,Copy File
  block:
    - name: Debug_Msg_2
      debug:
        msg: directory is exists
    - name: Copy File
      copy:
        src: Hello.txt
        dest: "{{ item }}"
      with_items:
        - ~/T01/Test1
        - ~/T01/Test2
  when: check_1.results[0].stat.exists

- name: msg,Create Directory
  block:
    - name: Debug Msg_1
      debug: 
        msg: directory is null
    - name: Create Directory Now
      file:
        dest: "{{ item }}"
        state: directory
      with_items:
        - ~/T01/Test1
        - ~/T01/Test2
  when: not check_1.results[0].stat.exists
      #- name: Copy TXT
      #  copy:
      #    src: Hello.txt
      #    dest: "{{ item }}"
      #  with_items:
      #    - ~/T01/
